version: '3'
services:
  nextjs:
    build: ./
    depends_on: 
      - mongo
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017-27019:27017-27019'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: alex
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_SITE_BASEURL: /api/mongoadmin/
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=svfsck2
      - POSTGRESQL_DATABASE=hangfire
    volumes:
      - pgdata:/bitnami
  hangui:
    image: hangui
    restart: always
    build:
      context: .
      dockerfile: ./hangfire/Hangfire.UI/Dockerfile
    ports:
      - '5005:80'
    depends_on:
      - postgresql 
  hangserver:
    image: hangserver
    restart: always
    build:
      context: .
      dockerfile: ./hangfire/Hangfire.Server/Dockerfile
    depends_on:
      - postgresql
      - hangui
  nginx:
    build: ./nginx
    depends_on: 
      - nextjs
      - hangui
    ports:
      - 80:80

volumes:
  portainer_data:
  pgdata: