version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:  
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: npm i -D cypress
      - run: npm run test:ci