version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
jobs:
  cacheBuild:
    executor: cypress/base-10
    steps:
      - attach_workspace:
        at: ~/repo
      - save_cache:
          key: v2-build-{{ checksum "package.json" }}
          paths:
            - .next/cache
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build'
          pre-steps:
            - restore_cache:
                keys:
                  - v2-build-{{ checksum "package.json" }}
      - cacheBuild:
          requires:
            - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          start: npm run start
          wait-on: 'http://localhost:3000'
          store_artifacts: true
          parallel: true
          parallelism: 4
          group: 'all tests'
          no-workspace: true
