version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build'
          pre-steps:
            - restore_cache:
              keys:
                - v2-build-{{ checksum "package.json" }}
              paths:
                - .next/cache
          post-steps:
            - save_cache:
              keys:
                - v2-build-{{ checksum "package.json" }}
      - cypress/run:
          requires:
            - cypress/install
          start: npm run start
          wait-on: 'http://localhost:3000'
          store_artifacts: true
          parallel: true
          parallelism: 4
          group: 'all tests'
          no-workspace: true
