version: 2.1
orbs:
  cypress: cypress-io/cypress@1.22.0
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - save_cache:
          paths:
            - node_modules
            - .next/cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm i -D cypress
      - run: npm run test:lint
      - run: npm run test:ci
